name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
        lua: [lua54, lua53, lua52, lua51]
        include:
        - os: ubuntu-22.04
          target: x86_64-unknown-linux-gnu
        - os: macos-latest
          target: x86_64-apple-darwin
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        target: ${{ matrix.target }}
    - name: Run ${{ matrix.lua }} tests
      run: |
        cargo build --features "${{ matrix.lua }}"
        (cd testcrate && cargo test --features ${{ matrix.lua }})
      shell: bash

  test_module:
    name: Test module
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
        include:
        - os: ubuntu-22.04
          target: x86_64-unknown-linux-gnu
        - os: macos-latest
          target: x86_64-apple-darwin
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        target: ${{ matrix.target }}
    - name: Install dependencies (macos)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew install lua luarocks
        luarocks make
      shell: bash
    - name: Install dependencies (linux)
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y lua5.1 liblua5.1-dev luarocks
        luarocks-5.1 --local make
      shell: bash
    - name: Run module inside Lua
      run: |
        eval `luarocks path`
        lua -e 'print(require("ryaml").encode({}))'
      shell: bash

  test_module_windows:
    name: Test module on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        include:
        - os: windows-latest
          target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: 5.4.6
      - name: Install luarocks
        run: |
          curl -L -O https://luarocks.org/releases/luarocks-3.9.2-windows-64.zip
          unzip -j luarocks-3.9.2-windows-64.zip -d .lua/bin
          rm -rf luarocks-3.*
          cp .lua/lib/lua54.dll .lua/bin
        shell: bash
      - name: Build module
        run: luarocks --tree .lua make
      - name: Run module inside Lua
        run: |
          lua -e 'print(require("ryaml").encode({}))'
        shell: bash

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - run: cargo fmt -- --check
